name: approle-cli

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=http://54.91.245.169:8200/
                  vault version
                  vault login ${{ secrets.APPROLEVAULT}}
               
                  echo "vault login success"
                 
              
                  myuser=$(vault kv get secret/mysql/webapp | grep username | awk '{ print $2; }')
                  mypass=$(vault kv get secret/mysql/webapp | grep password | awk '{ print $2; }')
                  mydb=$(vault kv get secret/mysql/webapp | grep db-name | awk '{ print $2; }')
               
                 
