name: approle

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://54.91.245.169:8200/
                #token:hvs.CAESIEIsGHauQ1QAwXlkZdO5llsDJWnI2EM8v6r_aSIiN9u5Gh4KHGh2cy5saVFQNzVVZ1hVZ003dndBNTg0Z0U2QzU 
                #token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                method: approle
                roleId: ${{ secrets.VAULT_ROLE_ID }}
                secretId: ${{ secrets.VAULT_SECRET_ID }}
                secrets: | 
                    secret/mysql/webapp username | USERNAME ;
                    secret/mysql/webapp password | PASSWORD ;
                    secret/mysql/webapp db-name | DBNAME 
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  username_id = ${{ env.USERNAME }} 
                  password_id = ${{ env.PASSWORD }}
                  dbname_id = ${{ env.DBNAME }}
                  region = us-east-1"
                  aws --version  
