name: vault-cubby-1

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
                  export VAULT_TOKEN=hvs.CAESIFOpEzkJuE-RQuQOjlolVbCJBPIIo7_EkCJqJGBW_htHGigKImh2cy42UExEZVA0NEZHV1UxS29VQk1VQW1ZOGcuVHFIZWkQrI0B
                 
                  vault version
                  vault login hvs.CAESIFOpEzkJuE-RQuQOjlolVbCJBPIIo7_EkCJqJGBW_htHGigKImh2cy42UExEZVA0NEZHV1UxS29VQk1VQW1ZOGcuVHFIZWkQrI0B
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  vault kv put -mount=kv creds-1 username=my-long-passcode password=123456
                  #retrive vaule from vault (kv engine) 
                  vault kv get -mount=kv creds-1
                  myval=$(vault kv get -mount=kv creds-1 | grep username | awk '{ print $2; }')
                  echo "$myval"
                  
                  mypass=$(vault kv get -mount=kv creds-1 | grep password | awk '{ print $2; }')
                  echo "$mypass"
                  #vault write cubbyhole/jfrog-cred1 username=renuka.prasad@cloudzenix.com password=Prasad@123 URL=https://cloudzenix.jfrog.io/
                  
                  #echo "print vault secrets"
                  
                  #myval=$(vault read cubbyhole/jfrog-cred1 | grep username | awk '{ print $2; }')
                  #echo "$myval"
                  
                  #mypass=$(vault read cubbyhole/jfrog-cred1 | grep password | awk '{ print $2; }')
                  #echo "$mypass"











