name: tf-kr-cubby

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
                  export VAULT_TOKEN=hvs.CAESIFOpEzkJuE-RQuQOjlolVbCJBPIIo7_EkCJqJGBW_htHGigKImh2cy42UExEZVA0NEZHV1UxS29VQk1VQW1ZOGcuVHFIZWkQrI0B
                 
                  vault version
                  vault login  hvs.CAESIFOpEzkJuE-RQuQOjlolVbCJBPIIo7_EkCJqJGBW_htHGigKImh2cy42UExEZVA0NEZHV1UxS29VQk1VQW1ZOGcuVHFIZWkQrI0B
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  #vault namespace create training
                  vault policy write my-policy-$ns - << EOF

                    path "${ns//\/}/" { 
                    capabilities = [ "read", "create", "update", "delete", "sudo", "list" ] 
                    }

                    path "${ns//\/}/secret/data/*" {
                    capabilities = ["deny"]
                    }

                    path "${ns//\/}/secret/metadata"

                    {
                   capabilities = [ "deny"]
                    }

                   EOF
                 
                  #echo "path "sys/namespaces/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" > edu-admin.hcl
                  #echo "path "sys/policies/acl/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  #echo "path "sys/mounts/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  #echo "path "sys/mounts" {capabilities = [ "read" ]}" >> edu-admin.hcl
                  #echo "path "identity/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  #echo "path "auth/token/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  #echo "path "edu-secret/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  export VAULT_NAMESPACE=admin/training
                  vault policy write -namespace=admin/training train-admin train-admin.hcl
                  export VAULT_NAMESPACE=admin/training
                  echo "success"
                  #vault kv put -mount=kv testjfrog username=cloudzenix.com password=Prasad url=https://cloudzenix.jfrog.io/
                  vault write cubbyhole/jfrog-cred username=renuka.prasad@cloudzenix.com password=Prasad@123 URL=https://cloudzenix.jfrog.io/
                  #vault read cubbyhole/myval
                  
                  echo "print vault secrets"
                  
                  mytoken=$(vault read cubbyhole/jfrog-cred | grep username | awk '{ print $2; }')
                  #echo "$mytoken"
                  
                  myvalue=$(vault read cubbyhole/jfrog-cred | grep password | awk '{ print $2; }')
                  #echo "$myvalue"
                  
                  
                  
            
