name: tf-kr-vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
                  export VAULT_TOKEN=hvs.CAESIMbMeLQjosN06RUVpPqxugQWcBLvcTTtQHKjlHGHXUB7GicKImh2cy5TVVR4TjBjdm1DTDZ0TGJuOXBDVWxTODIuVHFIZWkQuFY
                 
                  vault version
                  vault login hvs.CAESIMbMeLQjosN06RUVpPqxugQWcBLvcTTtQHKjlHGHXUB7GicKImh2cy5TVVR4TjBjdm1DTDZ0TGJuOXBDVWxTODIuVHFIZWkQuFY
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  #vault namespace create education

                 
                  #echo "path "sys/namespaces/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" > edu-admin.hcl
                  #echo "path "sys/policies/acl/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  #echo "path "sys/mounts/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  #echo "path "sys/mounts" {capabilities = [ "read" ]}" >> edu-admin.hcl
                  #echo "path "identity/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  #echo "path "auth/token/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  #echo "path "edu-secret/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  export VAULT_NAMESPACE=admin/education
                  #vault policy write -namespace=education edu-admin edu-admin.hcl
                  export VAULT_NAMESPACE=admin/education
                  #vault kv put -mount=kv testjfrog username=cloudzenix.com password=Prasad url=https://cloudzenix.jfrog.io/
                  
                  
                         
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
               # token: ${{ secrets.TFCVAULT }}
                token: hvs.CAESIMbMeLQjosN06RUVpPqxugQWcBLvcTTtQHKjlHGHXUB7GicKImh2cy5TVVR4TjBjdm1DTDZ0TGJuOXBDVWxTODIuVHFIZWkQuFY
                #caCertificate: ${{ secrets.VAULT_CA_CERT_HCP }}
                namespace: admin/education/
                exportToken: true
                secrets: |
                    /kv/testjfrog username  | USERNAME ;
                    /kv/testjfrog password  | PASSWORD 
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  username_id = ${{ env.USERNAME}} 
                  password_id = ${{ env.PASSWORD  }}
                  region = us-east-1"
                  aws --version     
           
