name: tf-kr-vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://vault-cluster-public-vault-09ee03a0.c7ad34bc.z1.hashicorp.cloud:8200/
                token: ${{ secrets.TFCVAULT }}
                caCertificate: ${{ secrets.VAULT_CA_CERT_HCP }}
                namespace: admin/education/
                exportToken: true
                secrets: |
                    /cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                    /cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY 
                    
           
