name: tf-kr-vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://portal.cloud.hashicorp.com/services/vault/vault-cluster?project_id=e0d0a913-bf69-4ade-8b8d-23fa910c9ddb
                token: ${{ secrets.TFCVAULT }}
                caCertificate: ${{ secrets.VAULT_CA_CERT_HCP }}
                namespace: admin/education/
                exportToken: true
                secrets: |
                    /cubbyhole/my-secret my-token  | MY-TOKEN ;
                    /cubbyhole/my-secret my-value  | MY-VALUE
           
