name: tf-kr-vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
                  export VAULT_TOKEN=hvs.CAESIOxAihjWD2qNMn6jLknWg0kCfIKHe9fsOac965V2QLpGGicKImh2cy56NlJFNk95bU5jcVc0OWxZd0RqMnd6VGkuVHFIZWkQ30Y
                  export VAULT_NAMESPACE=admin
                  vault version
                  vault login hvs.CAESIOxAihjWD2qNMn6jLknWg0kCfIKHe9fsOac965V2QLpGGicKImh2cy56NlJFNk95bU5jcVc0OWxZd0RqMnd6VGkuVHFIZWkQ30Y
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  

                  vault namespace create -namespace=admin/education 
                  cat>> edu-admin.hcl 
                         path "sys/namespaces/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}
                         path "sys/policies/acl/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}
                         path "sys/policies/acl" {capabilities = ["list"]}
                         path "sys/mounts/*" {capabilities = ["create", "read", "update", "delete", "list"]}
                         path "sys/mounts" {capabilities = [ "read" ]}
                         path "identity/*" {capabilities = ["create", "read", "update", "delete", "list"]}
                         path "auth/token/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}
                         path "edu-secret/*" {capabilities = ["create", "read", "update", "delete", "list"]}
                  edu-admin.hcl 
                  export VAULT_NAMESPACE=admin/education
                  vault policy write -namespace=education edu-admin edu-admin.hcl
                  export VAULT_NAMESPACE=admin/education
                  vault kv put -mount=kv JFrog username=renuka.prasad@cloudzenix.com password=Prasad@123 url=https://cloudzenix.jfrog.io/
                         
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://vault-cluster-public-vault-576b5917.b038600b.z1.hashicorp.cloud:8200/
                token: ${{ secrets.TFCVAULT }}
                caCertificate: ${{ secrets.VAULT_CA_CERT_HCP }}
                namespace: admin/education/
                exportToken: true
                secrets: |
                    /cubbyhole/my-secret my-token  | MY-TOKEN ;
                    /cubbyhole/my-secret my-value  | MY-VALUE  
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  username_id = ${{ env.MY-TOKEN }} 
                  password_id = ${{ env.MY-VALUE }}
                  region = us-east-1"
                  aws --version     
           
