name: tfcvault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v1.0.1
              with:
                url: https://vault-cluster-public-vault-2850ee0b.dcd5e1d1.z1.hashicorp.cloud:8200
                caCertificate: ${{ secrets.TFC_CA }}
                #method: approle/role/my-role
                method: approle
                #authPayload: |
                 # {
                roleId: ${{ secrets.VAULT_AUTOMATION_ROLE_ID }}
                secretId: ${{ secrets.VAULT_AUTOMATION_SECRET_ID }}

                #method: token
                #token: ${{ secrets.TFCVAULT }}
                #namespace: admin/
                secrets: |
                   cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                   cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY 
      
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }} 
                  aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
                  region = us-east-1"
                  aws --version 
