name: tfcvault

on:
#   push:
#     branches: [ master ] 
  workflow_dispatch:  


jobs:
    build:
         runs-on: ubuntu-latest
         steps:
          
#             - name: Import Secrets
#               uses: hashicorp/vault-action@v2.4.0
#               with:
#                 url: https://vault-cluster-public-vault-9d3cc5f0.ec174759.z1.hashicorp.cloud:8200
#                 #tlsSkipVerify: true
#                 #method: token
#                 token: ${{ secrets.TFCVAULT }} 
#                 #caCertificate: ${{ secrets.TFC_CA }}
#                 #method: approle
#                 #authPayload: |
#                 #roleId: ${{ secrets.VAULT_AUTOMATION_ROLE_ID }}
#                 #secretId: ${{ secrets.VAULT_AUTOMATION_SECRET_ID }}      
#                 #namespace: admin/
#                 exportToken: true
#                 secrets: |
#                     /infra/aws accesskey | AWS_ACCESS_KEY_ID ;
#                     /infra/aws secretkey | AWS_SECRET_ACCESS_KEY 
      
#             - name: Unit Test
#               run: |
#                   mkdir -p ~/.aws
#                   touch ~/.aws/credentials
#                   echo "[default]
#                   aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }} 
#                   aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
#                   region = us-east-1"
#                   aws --version 

            - name: Import Secrets
              uses: hashicorp/vault-action@v2.4.0
              env:
                CI: true
                ACTIONS_STEP_DEBUG: true
              with:
                url: https://vault-cluster-public-vault-9d3cc5f0.ec174759.z1.hashicorp.cloud:8200/
                #url: http://3.93.191.220:8200/
                method: approle
                caCertificate: ${{ secrets.TFC_CA }}
                token: ${{ secrets.TFC_VAULT_TOKEN }} 
                #token: ${{ secrets.VAULT}}
                authPayload: |
                  roleId: ${{ secrets.VAULT_AUTOMATION_ROLE_ID }}
                  secretId: ${{ secrets.VAULT_AUTOMATION_SECRET_ID }}      
                  namespace: admin
                exportToken: true
                secrets: |
                    /cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                    /cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY 

