name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                #url: http://54.89.147.158:8200
                url: https://vault-cluster-key-public-vault-2d7b4bd8.54f693ad.z1.hashicorp.cloud:8200
                #token: ${{ secrets.VAULT}}
                token: ${{ secrets.VAULT_TOKEN_KEY}}
                #caCertificate: ${{ secrets.VAULT_CA_CERT }}
                caCertificate: ${{ secrets.VAULT_CA_KEY}}
                secrets: |
                    /cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                    /cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY ;
                run: echo "$AWS_ACCESS_KEY_ID"
                

             # ...        
     
