name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://3.223.93.156:8200/
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: |
                  
                   /kv/JFrog username | USERNAME ;
                   /kv/JFrog password | PASSWORD
                   
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  username_id = ${{ env.USERNAME }} 
                  password_id = ${{ env.PASSWORD }}
                  region = us-east-1"
                  aws --version      
    











