name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=http://3.223.93.156:8200/
                  export VAULT_TOKEN=hvs.eETzcvWCkNIzZcSU8jVnhqtW
                 
                  vault version
                  vault login hvs.eETzcvWCkNIzZcSU8jVnhqtW
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  vault write cubbyhole/jfrog-cred username=renuka.prasad@cloudzenix.com password=Prasad@123 URL=https://cloudzenix.jfrog.io/
              

          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://3.223.93.156:8200/
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: | 
                    /cubbyhole/jfrog-cred username | USERNAME ;
                    /cubbyhole/jfrog-cred password | PASSWORD
                   
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  username_id = ${{ env.USERNAME }} 
                  password_id = ${{ env.PASSWORD }}
                  region = us-east-1"
                  aws --version      
    











