name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=http://3.223.93.156:8200/
                  export VAULT_TOKEN=hvs.eETzcvWCkNIzZcSU8jVnhqtW
                 
                  vault version
                  vault login hvs.eETzcvWCkNIzZcSU8jVnhqtW
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  vault namespace create education

                  echo "path "sys/namespaces/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" > edu-admin.hcl
                  echo "path "sys/policies/acl/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  echo "path "sys/mounts/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  echo "path "sys/mounts" {capabilities = [ "read" ]}" >> edu-admin.hcl
                  echo "path "identity/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  echo "path "auth/token/*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}" >> edu-admin.hcl
                  echo "path "edu-secret/*" {capabilities = ["create", "read", "update", "delete", "list"]}" >> edu-admin.hcl
                  export VAULT_NAMESPACE=admin/education
                  vault policy write -namespace=education edu-admin edu-admin.hcl
                  export VAULT_NAMESPACE=admin/education
                  #vault kv put -mount=kv testjfrog username=cloudzenix.com password=Prasad url=https://cloudzenix.jfrog.io/
                  vault write cubbyhole/myval my-token=s3cr3t88 my-value=asdffEE
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://3.223.93.156:8200/
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: | 
                    /cubbyhole/myval my-token | MY-TOKEN ;
                    /cubbyhole/myval my-value | MY-VALUE
                   
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  my-token_id = ${{ env.MY-TOKEN }} 
                  my-value_id = ${{ env.MY-VALUE }}
                  region = us-east-1"
                  aws --version      
    











