name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
          
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://3.223.93.156:8200/
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: |
                    /cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                    /cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY 
            - name: Unit Test
              run: |
                  mkdir -p ~/.aws
                  touch ~/.aws/credentials
                  echo "[default]
                  aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }} 
                  aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
                  region = us-east-1"
                  aws --version   


     
