name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://54.89.147.158:8200
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: |
                    /cubbyhole/foo accesskey | AWS_ACCESS_KEY_ID ;
                    /cubbyhole/foo secretkey | AWS_SECRET_ACCESS_KEY ;
                run:
                    echo accesskey = "${secrets.AWS_ACCESS_KEY_ID}"
                    echo secretkey = "${secrets.AWS_SECRET_KEY_ID}"
             # ...        
     
