name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            - name: VAULT COMMAND
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt install vault
                  sudo systemctl start vault.service
                  sudo systemctl status vault.service
                  export VAULT_ADDR=https://vault.cloudzenix.net
                  export VAULT_TOKEN=hvs.eETzcvWCkNIzZcSU8jVnhqtW
                 
                  vault version
                  vault login hvs.eETzcvWCkNIzZcSU8jVnhqtW
                  export VAULT_NAMESPACE=admin
                  echo "vault login success"
                  
                  vault kv put -mount=kv creds username=my-long-passcode password=123456
                  #retrive vaule from vault (kv engine) 
                  vault kv get -mount=kv creds
                  myval=$(vault kv get -mount=kv creds | grep username | awk '{ print $2; }')
                  echo "$myval"
                  
                  mypass=$(vault kv get -mount=kv creds | grep password | awk '{ print $2; }')
                  echo "$mypass"
                 # vault write cubbyhole/jfrog1-cred1 username=renuka1.prasad@cloudzenix.com password=Prasad@123 URL=https://cloudzenix.jfrog.io/
                  
                 # echo "print vault secrets"
                  
                 # myval=$(vault read cubbyhole/jfrog-cred1 | grep username | awk '{ print $2; }')
                 # echo "$myval"
                  
                  #mypass=$(vault read cubbyhole/jfrog-cred1 | grep password | awk '{ print $2; }')
                  #echo "$mypass"
                  
              

          
           # - name: Import Secrets
           #   uses: hashicorp/vault-action@v2
            #  with:
            #    url: http://3.223.93.156:8200/
             #   token: ${{ secrets.VAULT}}
             #   caCertificate: ${{ secrets.VAULT_CA_CERT }}
             #   secrets: | 
              #      /cubbyhole/jfrog-cred username | USERNAME ;
              #      /cubbyhole/jfrog-cred password | PASSWORD
                   
            #- name: Unit Test
            #  run: |
             #     mkdir -p ~/.aws
              #    touch ~/.aws/credentials
              #    echo "[default]
              #    username_id = ${{ env.USERNAME }} 
              #    password_id = ${{ env.PASSWORD }}
              #    region = us-east-1"
              #    aws --version      
    











